version: '3.8'

services:
  deathrun-db:
    image: mongo:latest
    container_name: deathrun-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongo-data: